# Generated by Django 5.1.6 on 2025-03-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="genero",
            field=models.CharField(
                choices=[("hombre", "Hombre"), ("mujer", "Mujer")],
                default="hombre",
                max_length=10,
            ),
        ),
    ]
