# Generated by Django 5.1.6 on 2025-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0003_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
