# Generated by Django 5.1.6 on 2025-03-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0004_alter_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
