# Generated by Django 5.1.6 on 2025-03-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0005_alter_producto_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
