# Generated by Django 5.1.6 on 2025-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0006_alter_producto_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                choices=[("perros", "Perros"), ("gatos", "Gatos"), ("otros", "Otros")],
                default="otros",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="edad_recomendada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cachorro", "Cachorro"),
                    ("adulto", "Adulto"),
                    ("senior", "Senior"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="tamano_mascota",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pequeño", "Pequeño"),
                    ("mediano", "Mediano"),
                    ("grande", "Grande"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
