# Generated by Django 5.1.6 on 2025-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0007_producto_categoria_producto_edad_recomendada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_reservado",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
