# Generated by Django 5.1.6 on 2025-03-16 18:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0009_pedido_detallepedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="fecha_pedido",
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pedido",
            name="iva",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total_con_iva",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("procesando", "En proceso"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
