# Generated by Django 5.1.6 on 2025-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mi_proyecto",
            "0010_remove_pedido_fecha_pedido_pedido_fecha_pedido_iva_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
