# Generated by Django 5.1.6 on 2025-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0011_alter_pedido_numero_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("procesando", "En proceso"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                ],
                default="pendiente",
                max_length=30,
            ),
        ),
    ]
