# Generated by Django 5.1.6 on 2025-03-30 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0013_rename_fecha_pedido_fecha_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="es_suscripcion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado_suscripcion",
            field=models.CharField(
                choices=[
                    ("activa", "Activa"),
                    ("pendiente_cancelacion", "Pendiente de cancelación"),
                ],
                default="activa",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Reseña",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, help_text="Tu nombre (opcional)", max_length=100
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Reseña")),
                (
                    "valoracion",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseñas",
                        to="mi_proyecto.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
