# Generated by Django 5.1.6 on 2025-04-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0020_customuser_direccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
