# Generated by Django 5.1.6 on 2025-05-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0021_pedido_lat_pedido_lng"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refugio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
