# Generated by Django 5.1.6 on 2025-05-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mi_proyecto", "0022_refugio"),
    ]

    operations = [
        migrations.CreateModel(
            name="MesEntregaSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_index", models.PositiveIntegerField()),
                ("entregado", models.BooleanField(default=False)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_mensuales",
                        to="mi_proyecto.pedido",
                    ),
                ),
            ],
            options={
                "unique_together": {("pedido", "mes_index")},
            },
        ),
    ]
